### ISSUE TITLE
Curling results in empty response, server crashes

### ISSUE THREAD

**Issue by jflory7** [unicef/coordinates_to_admin_id_server#3]
# Summary

`curl`ing against localhost results in empty response, server throws `ECONNREFUSED` and crashes

# Analysis

I followed the example in the README to see how the project worked, but I was unable to get the output demonstrated in the README. The server starts up as expected, but when I tried `curl`ing, it crashes and I don't receive the payload.

It's unclear to me as to why it's not able to retrieve the data.

# Expected results

<details>

```
$ curl http://localhost:8082/api/coordinates/33.385586,66.445313

{
  "iso": "AFG",
  "name_0": "Afghanistan",
  "name_1": "Daykundi",
  "name_2": "Gizab",
  "admin_id": "afg_1_6_53_gadm2-8",
  "lon": 66.445313,
  "lat": 33.385586
}
```

</details>

# Actual results

<details>

```
$ curl http://localhost:8082/api/coordinates/33.385586,66.445313
curl: (52) Empty reply from server

---

$ npm run build

> validate_schools@1.0.0 build /home/jflory/git/unicef/coordinates_to_admin_id_server
> babel src -d dist; node dist/server

src/helper.js -> dist/helper.js
src/router.js -> dist/router.js
src/search.js -> dist/search.js
src/server.js -> dist/server.js
Magic happens on port 8082
/home/jflory/git/unicef/coordinates_to_admin_id_server/dist/search.js:30
      if (err) throw err;
               ^

Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

</details>

**Comment by mikefab** [comment]
Did you complete the prerequisites?

- download_shapefiles_from_gadm
- import_shapefiles_to_postgres
